### ISSUE TITLE
Logging set to root

### ISSUE THREAD

**Issue by HorstSteuer** [mfeldt/AOSAT#3]
Currently the logging formatting etc. is applied to the root logger. This leads to the logging format of modules that import aosat being overwritten. I propose to define the logger on the package level. I.e., replace 'root' by __ package __ in aosat_cfg.py. For example:

`LOG_SETTINGS['root']['handlers'].append('file')`
by
`LOG_SETTINGS[__package__]['handlers'].append('file')`

**Comment by mfeldt** [comment]
I re-wrote the logging setup.  

I'm not an expert though,  could you check if it's more to your needs now?

**Comment by HorstSteuer** [comment]
Works perfectly. Thank you!
